kind: pipeline
type: docker
name: default
steps:
  - name: format
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make libffi go
      - make fmt
  - name: lint
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make libffi gcc go
      - make vet
  - name: proto
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make libffi gcc go git protobuf
      - go get -u github.com/gogo/protobuf/protoc-gen-gogo
      - GOPATH=/root/go PATH=$GOPATH/bin:$PATH make proto
  - name: build
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make libffi go
      - make build
    depends_on:
      - format
      - lint
      - proto
  - name: test
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm make libffi go
      - make test
    depends_on:
      - build
