kind: pipeline
type: docker
name: default
steps:
  - name: format
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm go
      - make fmt
  - name: lint
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm go
      - make vet
  - name: proto
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm go
      - go get -u github.com/gogo/protobuf/protoc-gen-gogo
      - make proto
  - name: build
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm go
      - make build
    depends_on:
      - format
      - lint
      - proto
  - name: test
    image: archlinux/base
    commands:
      - pacman -Sy --noconfirm go
      - make test
    depends_on:
      - build
